name: Build site into /docs (Pages branch deploy)

on:
  push:
    branches: [ main ]
    paths:
      - 'webapp/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-to-docs:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webapp
    env:
      BASE_PATH: ${{ endsWith(github.event.repository.name, '.github.io') && '/' || format('/{0}/', github.event.repository.name) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: webapp/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build with base path
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
        run: |
          echo "Using BASE_PATH=${BASE_PATH}"
          npm run build
          # SPA fallback + no Jekyll
          cp dist/index.html dist/404.html
          touch dist/.nojekyll

      - name: Publish to docs/ on main
        run: |
          cd ..
          rm -rf docs
          mkdir -p docs
          cp -R webapp/dist/* docs/
          # Ensure hidden file copied too
          cp webapp/dist/.nojekyll docs/.nojekyll
          # Commit only if there are changes
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A docs
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "docs: update site [skip ci]"
            git push
          fi

